# This file is added to get the Pulseaudio compiled
# with the bb file pointing to parity-PA with
# sound normalizer implementation on it
# This file will be removed once pulseaudio.bb points
# back to master pulseaudio code
; offload_normalizer_enable = true
; offload_normalizer_devicespeaker = true
; offload_normalizer_makeupgain = 15.0
; offload_normalizer_prefilter = true
; offload_normalizer_limiterthreshold = 5500
; offload_normalizer_limiterslope = 0.8
; offload_normalizer_compressorthreshold = 2000
; offload_normalizer_compressorslope = 0.42
; offload_normalizer_onoff = true
